export const KINDLE_MICRO_QUOTES = [
  "Morally Gray Approved",
  "Dark Romance Energy",
  "Chapter Damage",
  "Emotionally Booked",
  "Pretty & Dangerous",
  "Reader Energy",
  "Obsessed Respectfully",
  "Fictional Men Only",
  "Main Character Energy",
  "Reader Lifestyle",

  "Delulu Reader",
  "Reader Intuition",
  "Romance Brain",
  "Luxury Reader",
  "Plot Twist Era",
  "Reader Culture",
  "Bookish Energy",
  "Soft Life Reader",
  "Obsessed Reader",
  "Narrative Damage",

  "Chapter Spiral",
  "Kindle Girl Era",
  "Unhinged Reader",
  "Reader Logic",
  "Emotionally Literate",
  "Dark Romance Era",
  "Elite Reader Taste",
  "Booktok Energy",
  "Romance Culture",
  "High Standards Reader"
];
