export const STICKER_MICRO_QUOTES = [
  "Morally Gray Approved",
  "Dark Romance Energy",
  "Chapter 27 Damage",
  "Emotionally Booked",
  "Pretty & Dangerous",
  "Soft but Delusional",
  "He Don’t Play About Her",
  "Main Character Energy",
  "Unhinged Respectfully",
  "Fictional Men Only",

  "Reader Energy",
  "Plot Twist Survivor",
  "Bookish Chaos",
  "Emotionally Invested",
  "Kindle Girl Era",
  "Book Hangover",
  "Obsessed Respectfully",
  "Reader Problems",
  "Plot Twist Damage",
  "Late Night Reader",

  "Delulu Reader",
  "Reader Brain",
  "Romance Brain",
  "Villain Defender",
  "Morally Gray Taste",
  "Reader Intuition",
  "Book Girlie Approved",
  "Elite Reader Taste",
  "Obsessed With Fiction",
  "Emotionally Attached",

  "Kindle After Dark",
  "Chapter Spiral",
  "Unstable Reader",
  "Emotionally Literate",
  "Romance Culture",
  "Luxury Reader",
  "Dark Romance Era",
  "Booktok Energy",
  "Obsessed Reader",
  "Story Damage",

  "Reader Logic",
  "Emotionally Booked",
  "Reader Lifestyle",
  "High Standards Reader",
  "Narrative Damage",
  "Chapter 32 Victim",
  "Plot Twist Era",
  "Reader Culture",
  "Obsessive Reading",
  "Romance Damage"
];
