export const STICKER_QUOTE_BANKS = {
  general: [
    "Booked, busy, and emotionally unstable.",
    "This book ruined me… 5 stars.",
    "Quiet because the plot is plotting.",
    "I read like I have secrets too.",
    "My standards are fictional and expensive.",
    "Booked, busy, and barely coping.",
    "Do not disturb: emotionally invested.",
    "One more chapter. Be serious.",
    "I’m not dramatic. The book is.",
    "Reading like this is a full-time job.",
    "I support fictional chaos only.",
    "I fear I have a type.",
    "Emotionally attached to page 247.",
    "Currently unavailable. Plot twist in progress.",
    "My peace is fictional and heavily annotated.",
    "I came for the plot and stayed for the damage.",
    "This chapter has me acting strange.",
    "I’m booked through the emotional collapse.",
    "I like my stories messy and my coffee strong.",
    "Too pretty to be this invested."
  ],

  darkRomance: [
    "Morally gray is my favorite color.",
    "He’s toxic. I’m literate.",
    "He’s dangerous. I’m interested.",
    "Possessive? Only on paper.",
    "If he’s unhinged, I’m listening.",
    "I choose the villain.",
    "I prefer him unhinged.",
    "He needs therapy. I need chapter 28.",
    "He’s the red flag and I’m colorblind.",
    "Morally gray. Financially elite.",
    "Touch her and die energy.",
    "I don’t need him good. I need him mine.",
    "He’s not stable. He’s devoted.",
    "This man is a problem and I’m seated.",
    "If he says mine, I’m listening carefully.",
    "I support obsessive fictional behavior only.",
    "Ruthless men and reckless decisions.",
    "That man is dangerous and well-written.",
    "The villain was always the better option.",
    "Unhinged devotion? Add to cart."
  ],

  funny: [
    "This book got me acting illiterate.",
    "He smirked and I lost custody of my common sense.",
    "Booked, busy, and barely coping.",
    "I support fictional chaos only.",
    "That man is a problem and I respect it.",
    "I fear I have a type.",
    "This chapter is personally attacking me.",
    "I came for the romance and stayed for the audacity.",
    "The plot thickened and so did my delusion.",
    "I was fine before chapter 19.",
    "He breathed and I folded.",
    "This e-reader knows too much.",
    "Mentally: in a penthouse with a red flag.",
    "I did not need this kind of stress tonight.",
    "He’s fictional and still wasting my time.",
    "If he growls, I’m gone.",
    "Me? Attached? To nonsense? Absolutely.",
    "This is not self-care. This is spiral management.",
    "I need sleep. Unfortunately, he’s obsessed.",
    "That man is fake and still got me stressed."
  ],

  urban: [
    "He don’t play about her.",
    "RICH. RUTHLESS. RUINED FOR HER.",
    "PROTECTIVE. POSSESSIVE. PAID.",
    "Street loyal. Financially elite. Soft for her.",
    "He said mine and everybody heard it.",
    "Real ones move quiet.",
    "Money, loyalty, and dangerous love.",
    "He’s calm until it’s about her.",
    "Respectfully… that man is dangerous.",
    "Silent but lethal about his woman.",
    "Paid, polished, and petty.",
    "He don’t talk much. He handles it.",
    "Bossed up and book obsessed.",
    "Pretty girls read dangerous men too.",
    "That man got money and menace.",
    "Street smart. Fine. Fictional. Fatal.",
    "Luxury, pressure, and a loaded stare.",
    "He got soft for her and mean for everybody else.",
    "Elite behavior with block energy.",
    "He look expensive and emotionally unavailable."
  ],

  softLife: [
    "Soft life. Strong boundaries.",
    "Peace looks expensive on me.",
    "Read, rest, repeat.",
    "Gentle with myself. Ruthless with my standards.",
    "Soft mornings. Sharp instincts.",
    "Luxury in every chapter.",
    "Calm mind. Dramatic books.",
    "Soft life reader energy.",
    "Protecting my peace and my reading time.",
    "Romance and relaxation only.",
    "My nervous system likes quiet and Kindle.",
    "Rested, moisturized, and deeply invested.",
    "Soft glam. Hard boundaries.",
    "My life is not an emergency.",
    "Delicate, but never desperate.",
    "Slow days. Good books. Better taste.",
    "Peace first. Plot twists second.",
    "I choose ease and expensive fictional men.",
    "Comfort, candles, and chapter 32.",
    "Soft life with sharp discernment."
  ],

  morallyGray: [
    "I prefer him unhinged.",
    "I choose the villain.",
    "He’s the red flag and I’m colorblind.",
    "Morally gray. Financially elite.",
    "He needs therapy. I need chapter 28.",
    "If he's morally gray, I'm seated.",
    "Unhinged but intentional.",
    "Villain behavior only.",
    "Dangerous but well-dressed.",
    "Obsessed respectfully.",
    "I don’t fix him. I observe him.",
    "I support dark motives and deeper pockets.",
    "He’s wrong. I’m still listening.",
    "That man is morally flexible and gorgeous.",
    "Ethics blurred. Interest activated.",
    "I like him a little corrupt.",
    "He’s not a hero. He’s mine adjacent.",
    "Questionable behavior, impeccable execution.",
    "Moral ambiguity with a luxury finish.",
    "He’s a bad idea in a tailored coat."
  ],

  iykyk: [
    "IYKYK: Plot twist: the villain reads too.",
    "IYKYK: Romance readers know that look.",
    "IYKYK: Morally gray is my comfort color.",
    "IYKYK: He said 'relax.' That’s never reassuring.",
    "IYKYK: If he says 'mine' calmly… run.",
    "IYKYK: Book girls don’t chase. We annotate.",
    "IYKYK: I support women’s rights. And women’s revenge arcs.",
    "IYKYK: My toxic trait? Believing he’ll choose me.",
    "IYKYK: Quiet men are suspiciously attractive.",
    "IYKYK: That man didn’t blink once. Automatic book boyfriend.",
    "IYKYK: Emotionally unavailable but literate.",
    "IYKYK: I read for the plot. The plot: him.",
    "IYKYK: Street smart. Library dangerous.",
    "IYKYK: If he’s calm during chaos… noted.",
    "IYKYK: Therapy helped. So did fictional men.",
    "IYKYK: Soft life. Hard boundaries.",
    "IYKYK: Peace is expensive. I paid in lessons.",
    "IYKYK: Romance readers recognize obsession.",
    "IYKYK: He didn’t raise his voice. That’s worse.",
    "IYKYK: Kindle charged. Standards higher.",
    "IYKYK: Some men flirt. Some men declare war.",
    "IYKYK: She healed quietly. Then upgraded everything.",
    "IYKYK: Reader logic: Red flags build character.",
    "IYKYK: He watches her like strategy.",
    "IYKYK: Love language: Provision and silence.",
    "IYKYK: Books taught me pattern recognition.",
    "IYKYK: Rich men whisper differently.",
    "IYKYK: Power moves don’t announce themselves.",
    "IYKYK: If he says 'handle it,' he already did.",
    "IYKYK: I like my romance dangerous. But disciplined.",
    "IYKYK: Street loyalty reads like poetry.",
    "IYKYK: Soft voice. Unreasonable standards.",
    "IYKYK: He looks expensive and problematic.",
    "IYKYK: My era? Quietly outgrowing everything.",
    "IYKYK: Villain energy. Gentle with her only.",
    "IYKYK: Some men text. Some men arrive.",
    "IYKYK: She reads people like chapters.",
    "IYKYK: Money talks. Old money barely speaks.",
    "IYKYK: Healing looks boring. Peaceful, though.",
    "IYKYK: He clocked the room first.",
    "IYKYK: The richest flex is calm.",
    "IYKYK: Book girls detect tension instantly.",
    "IYKYK: That man didn’t smile once. Suspiciously attractive.",
    "IYKYK: My type? Emotionally competent menace.",
    "IYKYK: He protects. Not performs.",
    "IYKYK: Readers know that stare.",
    "IYKYK: Ambition looks good on silence.",
    "IYKYK: Soft life requires ruthless boundaries.",
    "IYKYK: I read dark romance responsibly.",
    "IYKYK: Provider energy is audible.",
    "IYKYK: He doesn’t argue. He adjusts outcomes.",
    "IYKYK: Delusional? No. Plot aware.",
    "IYKYK: Some chemistry feels criminal.",
    "IYKYK: Fantasy men ruined mediocrity.",
    "IYKYK: Reader intuition never lies.",
    "IYKYK: Peace, money, and mutual obsession.",
    "IYKYK: She stopped begging. Everything improved.",
    "IYKYK: He noticed everything. Said very little.",
    "IYKYK: Book culture side effect: zero tolerance for weak men.",
    "IYKYK: A man who reads rooms.",
    "IYKYK: If he’s patient… dangerous.",
    "IYKYK: This feels like chapter thirty.",
    "IYKYK: The calm ones rewrite endings.",
    "IYKYK: He didn’t flirt. He assessed.",
    "IYKYK: Reader instinct: that silence means something.",
    "IYKYK: I fear no man. Except the observant ones.",
    "IYKYK: She read the room. Then the man.",
    "IYKYK: My standards? Fiction ruined them.",
    "IYKYK: He speaks softly. Everyone listens anyway.",
    "IYKYK: Book girls recognize calculated attention.",
    "IYKYK: If he’s calm in chaos… stay alert.",
    "IYKYK: The problem with readers? We notice patterns.",
    "IYKYK: He didn’t chase. He closed distance strategically.",
    "IYKYK: Some men date. Some men select.",
    "IYKYK: My type is calm authority.",
    "IYKYK: Romance readers clock devotion early.",
    "IYKYK: He watched her like a decision.",
    "IYKYK: Soft life. Hard discernment.",
    "IYKYK: That wasn’t flirting. That was claiming territory.",
    "IYKYK: Peace requires selective access.",
    "IYKYK: He noticed the small details. That’s the dangerous kind.",
    "IYKYK: Reader brain: why did he say it like that?",
    "IYKYK: She healed. Now everyone must behave.",
    "IYKYK: If he’s quiet and rich… trouble.",
    "IYKYK: The man didn’t smile once. I’m listening.",
    "IYKYK: Love language: competence and consistency.",
    "IYKYK: Book girls can smell obsession.",
    "IYKYK: He looked at her like strategy.",
    "IYKYK: Some tension is academic.",
    "IYKYK: I support women’s rights. And strategic pettiness.",
    "IYKYK: He protects without announcing it.",
    "IYKYK: Reader culture: we study micro-behavior.",
    "IYKYK: My toxic trait? Thinking the morally gray one is sincere.",
    "IYKYK: She didn’t glow up. She recalibrated.",
    "IYKYK: That man reads people too well.",
    "IYKYK: He asked one question. Now the room is nervous.",
    "IYKYK: The quiet ones always know more.",
    "IYKYK: Romance readers understand tone shifts.",
    "IYKYK: If he lowers his voice… it’s serious.",
    "IYKYK: Money changes how men move.",
    "IYKYK: He moves like outcomes are guaranteed.",
    "IYKYK: Reader intuition: that man is not normal.",
    "IYKYK: She stopped explaining herself. Peace followed.",
    "IYKYK: Obsessive devotion is suspiciously attractive.",
    "IYKYK: He didn’t compete. He replaced.",
    "IYKYK: Ambition looks quiet up close.",
    "IYKYK: You can tell who’s been through something.",
    "IYKYK: He studies her like rare literature.",
    "IYKYK: Some chemistry feels illegal.",
    "IYKYK: That wasn’t jealousy. That was territorial math.",
    "IYKYK: Book girls require narrative depth.",
    "IYKYK: He looks like he keeps secrets.",
    "IYKYK: Her standards upgraded mid-healing.",
    "IYKYK: Power recognizes power quickly.",
    "IYKYK: He didn’t interrupt once. That’s discipline.",
    "IYKYK: The richest energy is patience.",
    "IYKYK: Reader lifestyle side effect: extreme emotional literacy.",
    "IYKYK: That man didn’t react. He adjusted the situation.",
    "IYKYK: You can’t gaslight someone who reads.",
    "IYKYK: He’s gentle with her. Not with the world.",
    "IYKYK: My era? Privately becoming unstoppable.",
    "IYKYK: Romance readers know: devotion reveals itself quietly.",
    "IYKYK: He watched everyone. But chose her."
  ],

  readerMood: [
    "Plot twist detected.",
    "Emotionally compromised by chapter 12.",
    "Suspicious of everyone.",
    "This chapter changed my life.",
    "Trust no character.",
    "I saw the twist coming.",
    "This book is messy.",
    "I need answers immediately.",
    "Reading like a detective.",
    "Chapter damage confirmed.",
    "Jaw on floor. Kindle in hand.",
    "The tension is disrespectful.",
    "I knew something was off.",
    "This chapter is not sitting right with me.",
    "Everybody in this book is lying.",
    "I’m too pretty for this stress.",
    "That reveal just altered my chemistry.",
    "I’m reading with my guard up.",
    "This plot is behaving criminally.",
    "Mood: concerned and fully invested."
  ],

  bookishLuxury: [
    "Books, wealth, and bad decisions.",
    "Romance looks expensive.",
    "Luxury reader energy.",
    "Reading like a rich auntie.",
    "Champagne taste in fictional men.",
    "Penthouse reading energy.",
    "Soft glam reader life.",
    "Money and morally gray men.",
    "High standards, fictional men.",
    "Reading like the main character.",
    "Quiet luxury, loud reactions.",
    "This taste level is fictional and elite.",
    "Silk robe. Sharp instincts. Smut.",
    "Designer taste and destructive tropes.",
    "If it’s not luxe, I’m not moved.",
    "My delusion has marble floors.",
    "Luxury, longing, and a loaded chapter.",
    "This bookmark is premium and petty.",
    "Gloss, gold, and emotional damage.",
    "Expensive energy only."
  ],

  bde: [
    "Big energy. Low tolerance.",
    "He walk in like the room was paid for.",
    "Quiet but commanding.",
    "That calm dominance hit different.",
    "He don’t flex. He funds.",
    "Built like pressure.",
    "Secure men don’t argue.",
    "Low voice. High authority.",
    "That ‘come here’ without saying it energy.",
    "He ain’t loud. He lethal.",
    "Moves like he already won.",
    "Calm dominance. Zero noise.",
    "That man got presence and payroll.",
    "Expensive silence.",
    "He doesn’t chase. He appears."
  ],

  eliteDominance: [
    "He’s rich, rude, and ridiculously obsessed.",
    "Soft voice. Violent loyalty.",
    "He doesn’t argue. He acquires.",
    "If he wanted to, he funded it.",
    "Luxury, loyalty, and low tolerance.",
    "He said mine like a contract.",
    "Unhinged but well-funded.",
    "Possessive with portfolio diversification.",
    "Morally gray. Financially elite.",
    "He solves problems with wire transfers.",
    "Obsessive devotion, premium edition.",
    "He doesn’t chase. He owns.",
    "Dangerous. Devoted. Diversified.",
    "Old money calm. New money hunger.",
    "Tailored suit. Territorial energy."
  ],

  bossWoman: [
    "I’m the boss and the plot.",
    "Soft glam. Hard boundaries.",
    "I don’t chase. I choose.",
    "I said no—politely and permanently.",
    "My standards have a security system.",
    "I lead with confidence and receipts.",
    "I’m booked, paid, and protected.",
    "Pretty, powerful, and not available.",
    "I don’t compete. I collect wins.",
    "If I want it, it’s handled.",
    "I’m the main character and the director.",
    "I don’t beg. I negotiate.",
    "Power looks good on me.",
    "Luxury and leverage.",
    "Beautiful, strategic, and busy."
  ],

  girlyFeminine: [
    "Soft, spoiled, and still in control.",
    "Pretty in peace.",
    "Glossy lips, sharp boundaries.",
    "If it doesn’t feel feminine and funded, I don’t want it.",
    "Cute… but I bite politely.",
    "Bow on the outside, backbone on the inside.",
    "Feminine doesn’t mean fragile.",
    "Sweet voice. Serious standards.",
    "I deserve flowers and follow-through.",
    "Soft glam, zero stress.",
    "My life is pink-coded and protected.",
    "Romance me correctly or move around.",
    "Pretty girl with pattern recognition.",
    "Delicate aesthetic. Dangerous standards.",
    "Softness with structure."
  ],

  paranormal: [
    "Something wicked and well-written.",
    "I like my romance cursed and committed.",
    "If it bites, it buys.",
    "My type? Supernatural and devoted.",
    "If it has fangs, I’m sold.",
    "Cursed, claimed, and completely hooked.",
    "Ghosted? I prefer possessed.",
    "Magic, mayhem, and a man obsessed.",
    "If he’s immortal, he better be loyal.",
    "Hexes, heat, and happily ever after.",
    "Moonlit tension hits different.",
    "I don’t chase. I conjure.",
    "Paranormal plot. Unhinged devotion.",
    "He’s not human and that’s somehow better.",
    "A little haunted. A lot interested."
  ],

  thriller: [
    "Plot twists only. No spoilers.",
    "Trust issues but make it literary.",
    "I knew it. I just needed the chapter to prove it.",
    "If it’s calm, it’s a setup.",
    "Trust no one. Turn the page.",
    "Plot twist loading.",
    "Nothing is what it seems and I love it.",
    "I’m here for the secrets.",
    "Give me chills, not small talk.",
    "If it’s too quiet, someone’s lying.",
    "I read with my guard up.",
    "The clue was in chapter three.",
    "Page-turner with a side of paranoia.",
    "I’m not scared. I’m intrigued.",
    "Unreliable narrators are my weakness."
  ]
};
