export const CHAPTER_TITLE_BANK = {
  dangerous_mmc: [
    "The Man Everyone Watches",
    "Calm Men Are Worse",
    "The Quiet Threat",
    "The Man Who Doesn’t Repeat Himself",
    "The Man Who Already Knows",
    "The One The Room Adjusts To",
    "The Man Who Solves Problems",
    "The Man With Quiet Authority",
    "The One Who Watches Everything",
    "The Man Who Moves First",
    "The Calm Before Consequences",
    "The Man Who Ends Conversations",
    "The Man Who Notices Everything",
    "The Man Who Handles It Personally",
    "The Quiet King",
    "The Man Who Walks In Calm",
    "The Man With The Final Word",
    "The Man Who Changes Outcomes",
    "The Man The Room Respects",
    "The Man Who Moves Strategically"
  ],

  street_king_energy: [
    "The King Of The City",
    "The Man The Block Respects",
    "The Boss Everyone Calls",
    "The Man Who Runs The Night",
    "The One With The Last Word",
    "The King The Streets Trust",
    "The Man Who Built The Empire",
    "The Boss Of The Block",
    "The Man Who Owns The Room",
    "The City’s Favorite Problem",
    "The Man Everyone Works For",
    "The King Of The Corner Office",
    "The Man Who Commands Respect",
    "The One Who Runs The Game",
    "The Boss Nobody Questions",
    "The Man With The Reputation",
    "The King Everyone Knows",
    "The Man The Streets Fear",
    "The One Who Moves The City",
    "The Man Who Built The Throne"
  ],

  expensive_dangerous_men: [
    "The Man Who Looks Expensive",
    "The Man With The Dangerous Smile",
    "The Calm Man With Resources",
    "The Man With The Watchful Eyes",
    "The Man In The Tailored Suit",
    "The Man Who Looks Like Trouble",
    "The Man Who Moves Like Money",
    "The Man With Expensive Patience",
    "The Man Who Speaks Once",
    "The Man With Quiet Power",
    "The Man Who Looks Like Strategy",
    "The Man With The Controlled Temper",
    "The Man Who Moves Like Authority",
    "The Man Who Changes The Room",
    "The Man Who Looks Like Consequences",
    "The Man With The Calm Voice",
    "The Man Who Doesn’t Rush",
    "The Man Who Already Decided",
    "The Man Who Looks Like Control",
    "The Man Who Carries The Storm"
  ],

  black_romance_devotion: [
    "Soft For Her Only",
    "The Man Who Chose Her",
    "The Woman He Protects",
    "The Only One He Listens To",
    "The Woman He Watches",
    "The Man Who Said Mine",
    "The Woman Who Changed Him",
    "The Man Who Stood Beside Her",
    "The Woman Who Calms Him",
    "The Man Who Doesn’t Play About Her",
    "The Woman Who Gets His Patience",
    "The Man Who Picks One Woman",
    "The Woman Who Holds His Attention",
    "The Man Who Stays Loyal",
    "The Woman Who Has His Loyalty",
    "The Man Who Doesn’t Share",
    "The Woman He Chose Publicly",
    "The Man Who Guards Her Peace",
    "The Woman Who Has His Focus",
    "The Man Who Moves For Her"
  ],

  reader_mood: [
    "Emotionally Invested",
    "Reading With Suspicion",
    "That Man Is Not Normal",
    "This Chapter Is Dangerous",
    "The Plot Thickens",
    "Emotionally Compromised",
    "Reader Instinct Activated",
    "Watching The MMC Carefully",
    "Concerned For The FMC",
    "The Tension Is Criminal",
    "Chapter Thirty Trauma",
    "This Man Is Suspicious",
    "Trust Issues Activated",
    "Reading With My Guard Up",
    "Plot Twist Pending",
    "Emotionally Attached Again",
    "This Man Is A Problem",
    "I Need The Next Chapter",
    "Reader Panic Activated",
    "The Plot Is Plotting"
  ],

  black_booktok_energy: [
    "Street King. Soft For Her.",
    "Dangerous Man. Gentle With Her.",
    "Quiet Man. Loud Consequences.",
    "Calm Man. Serious Power.",
    "Rich Man. Dangerous Loyalty.",
    "The Man The City Fears",
    "The Woman The City Respects",
    "The King And His Queen",
    "The Man Who Doesn’t Chase",
    "The Woman He Chose",
    "The Calm One Is Worse",
    "The Man Who Watches First",
    "The Man Who Said Mine",
    "The Man With The Plan",
    "The Woman Who Runs His Heart"
  ]
};
