export const KINDLE_HIGHLIGHT_BANK = {
  dangerous_mmc: [
    "He said mine like he already cleared the room.",
    "That man doesn’t argue. He adjusts outcomes.",
    "He didn’t ask what happened. He asked who.",
    "That man listens quietly and remembers everything.",
    "He noticed something nobody else did.",
    "He said handle it like the problem was already solved.",
    "He didn’t react. He recalculated.",
    "That man studies people like case files.",
    "He moves like outcomes belong to him.",
    "That man walks in calm and the room reorganizes itself.",
    "He said my name like the conversation was already finished.",
    "That man doesn’t repeat himself.",
    "His patience feels expensive.",
    "He speaks softly like he owns time.",
    "That man doesn’t rush because he knows the ending."
  ],

  calm_authority: [
    "He doesn’t raise his voice. He raises standards.",
    "Authority sits comfortably on him.",
    "He speaks once and the room adjusts.",
    "Confidence is quiet when it’s real.",
    "The room shifts when certain men enter it.",
    "Real dominance is calm under pressure.",
    "He commands attention without asking.",
    "Authority doesn’t ask for permission.",
    "The most dangerous men stay calm.",
    "That man moves with quiet certainty.",
    "Authority without arrogance.",
    "He controls the pace of the room.",
    "His silence carries authority.",
    "Leadership looks effortless on him."
  ],

  quiet_menace: [
    "The quiet ones always know more.",
    "That man didn’t smile once. Suspiciously attractive.",
    "He watches everyone before speaking.",
    "That man reads the room before anyone else does.",
    "Silence looks different on powerful men.",
    "He notices details nobody else catches.",
    "That man observes first and moves second.",
    "His calm feels deliberate.",
    "You can tell when someone knows the ending already.",
    "That man looks like strategy in motion.",
    "His silence says enough.",
    "He studies people like information.",
    "The quiet men always see everything."
  ],

  obsession: [
    "That man is dangerously in love and not hiding it.",
    "He said her name like a decision he already made.",
    "Everyone else saw obsession. She saw devotion.",
    "That man is down bad and moving accordingly.",
    "He fell first, hardest, and permanently.",
    "The room knew before she did.",
    "He watches her like she’s the only plan that matters.",
    "He lost interest in the world the moment he met her.",
    "That man is embarrassingly devoted.",
    "He doesn’t flirt. He commits aggressively.",
    "Everyone else is background noise.",
    "He’s loyal like it’s a contract.",
    "That man is permanently invested."
  ],

  provider_energy: [
    "He handles problems before she notices them.",
    "Providing for her is personal.",
    "That man builds safety around her.",
    "He moves like her comfort is the mission.",
    "He guards her happiness carefully.",
    "He secures her life quietly.",
    "Protection comes naturally to him.",
    "He treats her peace like responsibility.",
    "That man solves problems silently.",
    "He prioritizes her stability.",
    "He keeps her life soft on purpose.",
    "Protection is instinct for him.",
    "Providing is how he loves."
  ],

  black_dark_romance: [
    "Street king energy. Soft for her only.",
    "The city fears him. She doesn’t.",
    "Dangerous man. Gentle with her.",
    "Ruthless king. Devoted lover.",
    "The block knows him. She knows him better.",
    "Power looks different when he chooses one woman.",
    "That man runs the city but listens to her.",
    "Street loyalty. Romantic obsession.",
    "The man the city fears chose her.",
    "Dangerous men love quietly.",
    "The streets respect him. She teases him.",
    "Ruthless reputation. Soft devotion.",
    "The king bows only to her."
  ],

  luxury_romance: [
    "Rich men whisper differently.",
    "Money changes how men move.",
    "Power doesn’t announce itself.",
    "The richest energy is calm.",
    "Old money rarely raises its voice.",
    "Wealth moves quietly.",
    "Luxury looks calm from a distance.",
    "The most powerful men never rush.",
    "Money creates patience.",
    "The quiet ones usually own the room.",
    "Elegance is controlled power.",
    "Luxury men observe first.",
    "Authority looks expensive."
  ],

  reader_lifestyle: [
    "Books taught me pattern recognition.",
    "Reader intuition never lies.",
    "Book girls detect tension instantly.",
    "Readers know when the plot is plotting.",
    "You can’t gaslight someone who reads.",
    "Readers recognize obsession early.",
    "Book culture builds emotional intelligence.",
    "Readers notice micro-behavior.",
    "Reading builds suspicious instincts.",
    "Book girls recognize calculated attention.",
    "Readers know when something feels off.",
    "Romance readers clock devotion quickly.",
    "Book girls trust their instincts."
  ],

  tension_moments: [
    "That silence meant something.",
    "The way he said it changed everything.",
    "He noticed before anyone else.",
    "The room shifted when he looked at her.",
    "Something about that tone felt serious.",
    "The calm ones always rewrite endings.",
    "That man didn’t blink once.",
    "He said it too quietly.",
    "The tension arrived first.",
    "Everyone felt the moment change.",
    "The air shifted slightly.",
    "The conversation ended without warning.",
    "Something important just happened."
  ],

  villain_energy: [
    "I choose the villain.",
    "Morally gray is my comfort color.",
    "Dangerous men are suspiciously attractive.",
    "Villain energy. Gentle with her only.",
    "He protects. Not performs.",
    "Some chemistry feels criminal.",
    "Fantasy men ruined mediocrity.",
    "Romance readers recognize obsession.",
    "That man didn’t blink once.",
    "The villain reads too.",
    "That man isn’t safe. Interesting.",
    "Morally gray looks good on him.",
    "Villain devotion hits different."
  ],

  healing_soft_power: [
    "Soft life. Hard boundaries.",
    "Peace looks expensive.",
    "Healing looks boring. Peaceful though.",
    "She healed quietly.",
    "Some upgrades happen silently.",
    "Peace requires selective access.",
    "She stopped explaining herself.",
    "Boundaries look better with confidence.",
    "Calm life. Strong standards.",
    "Healing upgraded her standards.",
    "Peace is a luxury.",
    "She outgrew chaos.",
    "Soft life requires discipline."
  ],

  iykyk: [
    "IYKYK: Romance readers know that look.",
    "IYKYK: Morally gray is a lifestyle.",
    "IYKYK: If he says mine calmly… run.",
    "IYKYK: Quiet men are suspiciously attractive.",
    "IYKYK: That man didn’t blink once.",
    "IYKYK: The villain reads too.",
    "IYKYK: Romance readers recognize obsession.",
    "IYKYK: Some tension is academic.",
    "IYKYK: Fantasy men ruined mediocrity.",
    "IYKYK: Book girls detect tension instantly.",
    "IYKYK: That silence meant something.",
    "IYKYK: This feels like chapter thirty.",
    "IYKYK: The calm ones rewrite endings."
  ]
};
