export const MICRO_QUOTE_BANK = {
  general: [],
  dark_romance: [],
  funny_sarcastic: [],
  urban_fiction: [],
  soft_life: [],
  morally_gray: [],
  iykyk: [],
  reader_mood: [],
  bookish_luxury: [],
  bde_energy: [],
  elite_dominance: [],
  boss_woman: [],
  girly_feminine: [],
  paranormal: [],
  thriller: [],

  reader_culture: [],
  reader_chaos: [],
  viral_short: [],
  ultra_short: [],
  kindle_decal: [],
  dark_romance_girlie: [],
  power_energy: [],
  soft_life_reader: [],
  luxury_reader: [],
  urban_power: [],
  black_booktok_energy: [],
  funny_reader: []
};
