export const MICRO_QUOTE_BANK = {
  general: [
    "Peace was never promised.",
    "Plot twist energy only.",
    "Chaos looks good on me.",
    "Slightly dangerous standards.",
    "Romance with consequences.",
    "Emotionally unavailable men? Pass.",
    "Devoted psychos only.",
    "Booked And Dangerous",
    "Plot Twist Addicted",
    "Chapter Count Rising",
    "Fiction First Always",
    "Literary Chaos Pending",
    "Reader Instinct Strong",
    "Emotionally Plot Driven",
    "Plot Over Peace",
    "Chapter Energy Only",
    "Fictionally Committed"
  ],

  dark_romance: [
    "Red flags are bookmarks.",
    "Danger is attractive.",
    "Obsessed men only.",
    "Calm but lethal.",
    "Possessive respectfully.",
    "Violence but polite.",
    "Soft for me only.",
    "Villain Romance Approved",
    "Obsessed Man Enjoyer",
    "Dark Love Only",
    "Devotion With Danger",
    "Villain Era Activated",
    "Obsessive Energy Preferred",
    "Red Flag Appreciation Club",
    "Dangerously Devoted",
    "Possession Energy Only",
    "Morally Dark Taste"
  ],

  funny_sarcastic: [
    "Romanticizing poor decisions.",
    "Reading red flags again.",
    "Morally gray enthusiast.",
    "Fictional men supporter.",
    "Unhinged but literate.",
    "Plot over peace.",
    "Plot Made Me Do It",
    "Reading Instead Of Healing",
    "Book Before Responsibilities",
    "Delusion Fueled Reading",
    "Chapter Ruined My Night",
    "Emotionally Booked Again",
    "Plot Caused This",
    "Sleep Is Optional Tonight",
    "Reading Like Rent Due",
    "Emotionally Bamboozled"
  ],

  urban_fiction: [
    "City king energy.",
    "Loyalty over everything.",
    "Street smart romance.",
    "Dangerous reputation.",
    "Power couple pending.",
    "Street Romance Energy",
    "City King Approved",
    "Paid And Protective",
    "Loyalty Over Logic",
    "Boss Energy Romance",
    "Street Smart Love",
    "Pressure Makes Diamonds",
    "Real Ones Move Quiet",
    "Block Royalty Behavior",
    "Luxury With Edge"
  ],

  soft_life: [
    "Peacefully dramatic life.",
    "Silk sheet energy.",
    "Quiet luxury reader.",
    "Soft life loading.",
    "Resting in abundance.",
    "Peaceful Reader Era",
    "Soft Days Only",
    "Quiet Chapter Energy",
    "Protected Peace Mode",
    "Reading In Luxury",
    "Soft Life Chapters",
    "Calm Mind Reading",
    "Comfort First Always",
    "Rested Reader Energy",
    "Ease Over Everything"
  ],

  morally_gray: [
    "Morals negotiable.",
    "Good to me though.",
    "Ethically complicated love.",
    "Villain supporter.",
    "Questionable loyalty.",
    "Moral Compass Optional",
    "Villain Sympathizer",
    "Gray Area Romance",
    "Ethically Complicated Taste",
    "Morally Flexible Love",
    "Questionable But Fine",
    "Dark Motives Approved",
    "Devotion Without Rules",
    "Villain Behavior Appreciated",
    "Strategically Corrupt"
  ],

  iykyk: [
    "IYKYK: The tension matters.",
    "IYKYK: Chapter fifteen changes everything.",
    "IYKYK: Slow burn supremacy.",
    "IYKYK: That one chapter.",
    "IYKYK: Dangerous devotion.",
    "IYKYK: That Look Means Trouble",
    "IYKYK: Chapter Thirty Energy",
    "IYKYK: Reader Intuition Never Misses",
    "IYKYK: Calm Men Are Suspicious",
    "IYKYK: That Silence Was Loud",
    "IYKYK: He Noticed Everything",
    "IYKYK: This Feels Like A Plot Twist",
    "IYKYK: That Tone Meant War",
    "IYKYK: The Quiet Ones Win",
    "IYKYK: This Chapter Changed Everything"
  ],

  reader_mood: [
    "Mood: chaotic romance.",
    "Need fictional problems.",
    "Reader in hiding.",
    "Emotionally invested again.",
    "Ignoring responsibilities.",
    "Reading With Suspicion",
    "Emotionally In Chapter",
    "Plot Twist Anticipation",
    "Reader Panic Activated",
    "Chapter Anxiety Rising",
    "Plot Thickening Mood",
    "Emotionally Invested Again",
    "Suspicious Of Everyone",
    "Reading Like Investigation",
    "Story Stress Mode"
  ],

  bookish_luxury: [
    "Library over nightlife.",
    "Books are wealth.",
    "Expensive book taste.",
    "Collecting fictional husbands.",
    "Hardcover supremacy.",
    "Library Energy Only",
    "Luxury Reader Lifestyle",
    "Champagne Taste Books",
    "Expensive Reader Taste",
    "Elite Library Mood",
    "Designer Chapter Energy",
    "Rich Reader Vibes",
    "Penthouse Reading Club",
    "Gloss And Hardcovers",
    "Luxury Book Culture"
  ],

  bde_energy: [
    "Silent confidence only.",
    "Dominance detected.",
    "Authority looks good.",
    "Effortless power.",
    "Dominant Energy Present",
    "Quiet Confidence Mode",
    "Authority Detected",
    "Pressure In Motion",
    "Calm Control Energy",
    "Commanding Presence",
    "Silent Power Moves",
    "Effortless Authority",
    "Presence Over Volume",
    "Power Without Effort"
  ],

  elite_dominance: [
    "Power without noise.",
    "Elite energy only.",
    "Controlled authority.",
    "Legacy mindset.",
    "Legacy Energy Only",
    "Elite Man Behavior",
    "Power Moves Quietly",
    "Rich Man Authority",
    "Old Money Calm",
    "Dominance With Discipline",
    "High Power Presence",
    "Luxury Dominance Mode",
    "Quiet Empire Energy",
    "Strategic Power Moves"
  ],

  boss_woman: [
    "Self-made energy.",
    "Building my empire.",
    "Ambition looks good.",
    "CEO mindset.",
    "CEO Energy Activated",
    "Boss Mindset Only",
    "Power Move Pending",
    "Ambition First Always",
    "Winning Quietly",
    "Leader Energy Only",
    "Strategy Over Emotion",
    "Empire Builder Mood",
    "Authority Looks Good",
    "Successful And Unbothered"
  ],

  girly_feminine: [
    "Pretty and strategic.",
    "Lip gloss diplomacy.",
    "Feminine but fearless.",
    "Soft but calculating.",
    "Pretty Power Mode",
    "Soft Glam Authority",
    "Feminine Strategy Club",
    "Delicate But Dangerous",
    "Pretty Discipline Era",
    "Grace With Boundaries",
    "Elegant Control Energy",
    "Glossy Confidence Only",
    "Softness With Strength",
    "Pretty But Calculating"
  ],

  paranormal: [
    "Dating immortals again.",
    "Supernatural standards.",
    "Vampire approved.",
    "Monster romance club.",
    "Immortal Romance Taste",
    "Creature Love Club",
    "Magic Romance Energy",
    "Monster Devotion Approved",
    "Dark Magic Romance",
    "Moonlit Love Story",
    "Supernatural Attachment",
    "Cursed Love Interest",
    "Night Creature Romance",
    "Spellbound Love Energy"
  ],

  thriller: [
    "Suspiciously calm man.",
    "Trouble found me.",
    "Danger nearby.",
    "Survival instincts active.",
    "Suspense Reader Mode",
    "Mystery Instinct Activated",
    "Plot Twist Investigator",
    "Clue Hunter Energy",
    "Storyline Suspicious",
    "Reading Like Evidence",
    "Trust Issues Activated",
    "Suspense Addict",
    "Crime Plot Approved",
    "Twist Ending Energy"
  ],

  reader_culture: [
    "Chapter Addict",
    "Plot Devourer",
    "Kindle Loyalist",
    "Fiction Over Reality",
    "Page Turner Energy",
    "Literary Menace",
    "Annotate Everything",
    "Book Girl Behavior",
    "Late Night Chapters",
    "Literary Delusion",
    "Chapter Goblin Mode",
    "Plot Twist Pending",
    "Reader Brain Activated",
    "Emotionally Booked Again",
    "Chapter Addict Club",
    "Plot Twist Survivor",
    "Emotionally Bookmarked",
    "Reader Lifestyle Locked",
    "Kindle Loyalist Energy",
    "Page Turning Problems",
    "Reader Logic Activated",
    "Reader Era Activated",
    "Book Hangover Pending"
  ],

  reader_chaos: [
    "Chapter Gremlin",
    "Plot Goblin",
    "Reading Recklessly",
    "Book Spiral",
    "Literary Meltdown",
    "Chapter Damage",
    "Fiction Hangover",
    "Book Brain Rot",
    "Emotional Plot Twist",
    "Page Rage",
    "Plot Goblin Mode",
    "Chapter Goblin",
    "Romance Gremlin",
    "Literary Chaos Agent",
    "Emotionally Ruined",
    "Plot Twist Addict",
    "Fiction Damage",
    "Romance Spiral",
    "Page Turning Demon",
    "Kindle Goblin"
  ],

  viral_short: [
    "Reader Instincts",
    "Dangerous Taste",
    "Fiction Loyalist",
    "Bookish Authority",
    "Literary Obsession",
    "Chapter Discipline",
    "Fiction Priority",
    "Narrative Gremlin",
    "Bookish Menace",
    "Literary Control",
    "Plot Devotion",
    "Story Loyalty",
    "Chapter Strategy",
    "Fiction Strategy",
    "Narrative Power",
    "Reader Supremacy",
    "Elite Reader",
    "Page Authority",
    "Literary Instinct",
    "Reader Dominance"
  ],

  ultra_short: [
    "Plot Goblin",
    "Chapter Goblin",
    "Story Gremlin",
    "Reader Gremlin",
    "Book Goblin",
    "Plot Gremlin",
    "Story Goblin",
    "Reading Gremlin",
    "Chapter Gremlin",
    "Kindle Gremlin",
    "Page Addict",
    "Story Addict",
    "Romance Addict",
    "Plot Addict",
    "Book Addict",
    "Fiction Addict",
    "Series Addict",
    "Trope Addict",
    "Reading Menace",
    "Literary Menace",
    "Chaos Reader",
    "Plot Damage",
    "Chapter Damage",
    "Story Damage",
    "Reader Damage",
    "Romance Damage",
    "Emotional Damage",
    "Page Turner",
    "Reader Energy",
    "Book Energy",
    "Reader Problems",
    "Book Problems",
    "Plot Problems",
    "Story Problems",
    "Book Girlie",
    "Reader Girlie",
    "Kindle Girlie",
    "Romance Girlie",
    "Story Brain",
    "Reader Brain",
    "Book Brain",
    "Page Goblin",
    "Chapter Hunter",
    "Story Hunter",
    "Plot Hunter",
    "Trope Hunter",
    "Book Hunter",
    "Romance Hunter",
    "Reader Hunter",
    "Series Hunter"
  ],

  kindle_decal: [
    "Just One More Chapter",
    "Kindle Girlie Energy",
    "Romance Reader Life",
    "Late Night Chapters",
    "Booked For Tonight",
    "Reading In Progress",
    "Chapter Addict",
    "Romance Mode Activated",
    "Page Turner Era",
    "Reading All Weekend",
    "Plot Twist Incoming",
    "Story Mode On",
    "Reading Time Activated",
    "Romance Novel Mode",
    "Chapter Count Climbing",
    "Just Started Another Book",
    "Weekend Reading Plans",
    "Storytime For Adults",
    "Book Mode Only",
    "Reading All Night",
    "Kindle Never Sleeps",
    "Romance Reader Club",
    "Plot Twist Specialist",
    "Reading Mood Activated",
    "Chapter Time Only",
    "Story Addict Energy",
    "Romance Reader Forever",
    "Bookish Night Shift",
    "Page Turner Lifestyle",
    "Reading Is Happening",
    "Kindle Reading Club",
    "Bookworm Energy Only",
    "Chapter Loading",
    "Plot Twist Anticipation",
    "Reading Life Chosen",
    "Chapter Thirty Incoming",
    "Romance Reading Hours",
    "Reading Habit Formed",
    "Storytime Specialist",
    "Plot Driven Life",
    "Reading Plans Cancelled",
    "Book First Always",
    "Romance Reader Mood",
    "Chapter Hunter",
    "Book Lover Era",
    "Reading Is Mandatory",
    "Plot Twist Approved",
    "Kindle Life Chosen",
    "Page Turner Mindset",
    "Story Mode Forever"
  ],

  dark_romance_girlie: [
    "Obsessive Fiction Enjoyer",
    "Dark Romance Devotee",
    "Book Villain Supporter",
    "Obsessed MMC Society",
    "Protective Alpha Approved",
    "Devotion Over Decency",
    "Fictional Menace Lover",
    "Obsessive Book Boyfriend",
    "Possessive Romance Approved",
    "Morally Questionable Crush",
    "Dark Love Enthusiast",
    "Book Villain Fan Club",
    "Devotion With Attitude",
    "Protective Man Preference",
    "Obsessed Male Lead Club",
    "Book Boyfriend Loyalist",
    "Dark Romance Addict",
    "Obsessed Man Agenda",
    "Devoted Alpha Preference",
    "Morally Gray Devotion",
    "Possessive Hero Enjoyer",
    "Dark Romance Mindset",
    "Book Villain Defender",
    "Obsessed Hero Energy",
    "Protective Romance Culture",
    "Devoted Man Enthusiast",
    "Book Boyfriend Society",
    "Possessive MMC Approved",
    "Dark Romance Standards",
    "Obsessed Hero Supporter",
    "Protective Alpha Culture",
    "Devoted MMC Energy",
    "Book Villain Enthusiast",
    "Obsessed Romance Taste",
    "Possessive Love Agenda",
    "Dark Romance Identity",
    "Devotion Lover Club",
    "Morally Gray Romance Club",
    "Book Boyfriend Agenda",
    "Obsessed Hero Taste",
    "Protective MMC Preference",
    "Dark Romance Girlie",
    "Devoted Man Club",
    "Possessive Fiction Culture",
    "Morally Gray Boyfriend",
    "Obsessed MMC Energy",
    "Dark Romance Society",
    "Devoted Alpha Energy",
    "Book Villain Appreciation",
    "Obsessed Hero Era"
  ],

  power_energy: [
    "Calm Authority",
    "Command Presence",
    "Silent Control",
    "Strategic Power",
    "Quietly Dangerous",
    "Elite Energy",
    "Dominance Detected",
    "Pressure Built",
    "Calm But Lethal",
    "Power Move Pending",
    "Dominant Energy Detected",
    "Presence Over Noise",
    "Authority Without Effort",
    "Silent Power Moves",
    "Controlled Menace Energy",
    "Quiet Power Detected",
    "Elite Man Behavior",
    "Calm Pressure Energy"
  ],

  soft_life_reader: [
    "Cozy Chapter Club",
    "Peaceful Reading",
    "Silk Sheet Reader",
    "Soft Reader Life",
    "Quiet Chapter Energy",
    "Candlelight Reading",
    "Rest & Read",
    "Calm Chapter Mood",
    "Luxury Reading Time",
    "Protected Peace"
  ],

  luxury_reader: [
    "Old Money Energy",
    "Rich Behavior",
    "Elite Taste Only",
    "Luxury Standards",
    "Premium Delusion",
    "Rich Girl Reading",
    "Silk Robe Era",
    "Penthouse Energy",
    "Gloss & Gold",
    "Diamond Standards"
  ],

  urban_power: [
    "Street King Energy",
    "Dangerous Loyalty",
    "Paid & Protected",
    "Respect The Queen",
    "City Boss Energy",
    "Loyalty First",
    "Block Royalty",
    "Ruthless Romance",
    "Street Legend Energy",
    "Silent Protector"
  ],

  black_booktok_energy: [
    "Street King. Soft For Her.",
    "Dangerous Man. Gentle With Her.",
    "Quiet Man. Loud Consequences.",
    "Calm Man. Serious Power.",
    "Rich Man. Dangerous Loyalty.",
    "The Man The City Fears",
    "The Woman The City Respects",
    "The King And His Queen",
    "The Man Who Doesn’t Chase",
    "The Woman He Chose",
    "The Calm One Is Worse",
    "The Man Who Watches First",
    "The Man Who Said Mine",
    "The Man With The Plan",
    "The Woman Who Runs His Heart"
  ],

  funny_reader: [
    "Fictionally Delusional",
    "Plot Victim",
    "Chapter Survivor",
    "Book Induced Chaos",
    "Romance Ruined Me",
    "Page Turning Problems",
    "Bookish Instability",
    "Literary Bad Decisions",
    "Fiction First",
    "Book Before People",
    "Bookstore Budget Destroyer",
    "Professionally Overthinking Fiction",
    "Reading Instead Of Socializing",
    "Emotionally Held Hostage By A Plot",
    "Romance Novel Survival Club",
    "Chapter Hoarder Behavior",
    "Fiction Made Me Like This",
    "Plot Twist Therapy Session",
    "Mentally Living In A Series",
    "Emotionally Sponsored By Books",
    "Chronically In A Reading Slump",
    "Bookstore Trips Are Self Care",
    "Plot Twist Recovery Team",
    "Emotionally Damaged By Chapter Twenty",
    "Weekend Plans: Fictional Problems",
    "Book Club Without The Club",
    "Professional Story Analyzer",
    "Romance Reader Support Group",
    "Chronically Starting New Books",
    "Reading Through Emotional Turmoil",
    "Certified Page Turner Addict",
    "Fictional Worlds Residency",
    "Reading Until Further Notice",
    "Emotionally Employed By Plotlines",
    "Bookstore Energy Only",
    "Romance Reader Rehabilitation",
    "Living Off Plot Twists",
    "Emotionally Invested Citizen",
    "Bookish Escapism Department",
    "Reading Is My Personality",
    "Storyline Stress Survivor",
    "Emotionally Dependent On Fiction",
    "Weekend Reading Marathoner",
    "Literary Drama Consumer",
    "Books Ruined My Expectations",
    "Emotionally Attached To Characters",
    "Plotline Investigation Team",
    "Reading My Way Through Chaos",
    "Fiction Over Social Plans",
    "Reader Identity Confirmed"
  ]
};
