export const QUOTE_BANK = {
  general: [],
  dark_romance: [],
  funny_sarcastic: [],
  urban_fiction: [],
  soft_life: [],
  morally_gray: [],
  iykyk: [],
  reader_mood: [],
  bookish_luxury: [],
  bde_energy: [],
  elite_dominance: [],
  boss_woman: [],
  girly_feminine: [],
  paranormal: [],
  thriller: [],

  dangerous_mmc: [],
  quiet_menace_mmc: [],
  provider_alpha_mmc: [],
  obsessed_disciplined_mmc: [],
  down_bad_mmc: [],
  public_claim_mmc: [],
  wife_energy_mmc: [],
  jealous_controlled_mmc: [],
  strategy_mmc: [],
  expensive_dangerous_mmc: [],
  calm_authority_mmc: [],
  soft_voice_serious_mmc: [],
  provider_unhinged_mmc: [],
  she_calms_him: [],
  he_only_chases_her: [],
  everyone_fears_him_except_her: [],
  city_respects_her_because_of_him: [],
  he_said_mine_quietly: [],

  black_romance_devotion: [],
  street_king_soft_for_her: [],
  obsessed_rich_man_hood_girl: [],
  street_king_soft_life: [],
  black_dark_romance_obsession: [],
  black_romance_kindle_highlights: []
};
