export const QUOTE_BANK = {
  general: [
    "Some women want flowers. I want a man who reads the room and chooses violence on my behalf.",
    "My love language is a man who listens carefully… and then ignores my protests anyway.",
    "I didn’t ask for a soft life. I asked for a dangerous man who only softens for me.",
    "Peace is cute, but have you ever been adored by a man who scares everyone else?",
    "I don’t chase men. I attract problems with excellent jawlines.",
    "My standards aren’t high. They’re just terrifying to mediocre men.",
    "I don’t fall in love easily. But when I do, chaos usually follows.",
    "I read like someone is going to test me on emotional damage later.",
    "If the book ruins my peace, it’s automatically five stars.",
    "I didn’t lose sleep. I invested it into the plot.",
    "My hobbies include reading and emotionally recovering from reading.",
    "Fictional men have raised my standards to a legally unreasonable level.",
    "If the chapter is calm, I know the author is planning something criminal.",
    "I’m not addicted to books. I’m committed to narrative outcomes."
  ],

  dark_romance: [
    "I never wanted a safe man. I wanted the one people warned me about.",
    "The way he looks at me makes good decisions feel optional.",
    "He’s not the hero of the story. But he’s very committed to keeping me alive.",
    "The world thinks he’s dangerous. I just think he’s mine.",
    "He doesn’t promise peace. He promises loyalty.",
    "The scariest thing about him isn’t his temper. It’s how gentle he is with me.",
    "Loving him feels like signing a contract written in fire.",
    "I never said I wanted a good man. I said I wanted a devoted one.",
    "The more dangerous he looks, the more comfortable I get.",
    "Some women want stability. I want a man who scares the room.",
    "If he says mine calmly, the plot just got interesting.",
    "I support morally gray decisions when they are extremely well executed.",
    "Fictional men commit crimes but at least they commit emotionally too.",
    "If the villain is obsessed with her, I’m already on his side."
  ],

  funny_sarcastic: [
    "My toxic trait is believing the red flag is just character development.",
    "I read dark romance for the plot. The extremely suspicious plot.",
    "Therapy is expensive. Books about morally questionable men are $12.99.",
    "If loving fictional criminals is wrong, I refuse to be right.",
    "I support women’s rights and women’s wrong decisions in dark romance.",
    "My type? Emotionally stable in public, unhinged about me in private.",
    "If the man isn’t slightly feral, I’m returning the book.",
    "I opened the book for fun and now I’m emotionally unemployed.",
    "I read one chapter and suddenly my entire personality is concerned.",
    "That man is fictional and still causing me unnecessary stress.",
    "I didn’t expect the plot to attack me personally like this.",
    "This book is ruining my sleep schedule and I respect it.",
    "If he smirks one more time I’m filing a complaint with the author."
  ],

  urban_fiction: [
    "I didn’t fall for the king of the city. I fell for the way the city moves when he walks in.",
    "The streets respect him. I just happen to love him.",
    "Power looks different when you’re the woman standing beside it.",
    "Loyalty isn’t romantic until you see what a man is willing to risk for you.",
    "Everybody fears him. I’m the only one he listens to.",
    "He built an empire. I built the patience to survive loving him.",
    "When he said mine, the entire city understood the assignment.",
    "The streets fear him but somehow he listens to her.",
    "Loyalty looks different when a powerful man chooses one woman.",
    "That man runs the city but she runs his patience.",
    "Dangerous men are calm until it’s about her.",
    "He doesn’t explain himself. The results do that.",
    "Money, power, and a man who refuses to play about her."
  ],

  soft_life: [
    "My version of soft life includes silk sheets and a man who handles problems before I hear about them.",
    "Peace is waking up knowing someone dangerous is protecting your quiet.",
    "Soft life isn’t laziness. It’s strategic comfort.",
    "I prayed for peace and somehow received a man who eliminates problems.",
    "My only responsibility is choosing which book to read next.",
    "Luxury is emotional safety with a hint of chaos.",
    "Soft life means my only problem today is choosing the next book.",
    "Peace feels better when you fought hard enough to recognize it.",
    "My version of luxury includes silence and uninterrupted reading.",
    "A soft life is built, protected, and defended.",
    "Calm days and chaotic fictional men balance the universe.",
    "Protecting my peace is my most successful habit."
  ],

  morally_gray: [
    "I never said he was a good man. I said he was good to me.",
    "Morally gray men love harder because they choose you anyway.",
    "He doesn’t follow rules. He follows me.",
    "The world calls him dangerous. I call him dependable.",
    "I sleep peacefully knowing he would ruin someone’s life for me.",
    "Ethics are flexible when devotion is absolute.",
    "Morally gray men love harder because they know exactly what they are.",
    "I don’t need him perfect. I need him loyal.",
    "The world calls him dangerous. I call him consistent.",
    "Morally gray just means he knows who deserves mercy and who doesn’t.",
    "He’s not the hero, but he’s very committed to protecting her story.",
    "A man who breaks rules for you is more interesting than one who follows them."
  ],

  iykyk: [
    "IYKYK: The red flag chapters always end up being the best ones.",
    "IYKYK: The more unhinged the man, the more respectful he is to her.",
    "IYKYK: If the book starts peaceful, chaos is already on the way.",
    "IYKYK: The man everyone fears is always obsessed with one woman.",
    "IYKYK: The slow burn always turns into wildfire.",
    "IYKYK: The quieter the man, the worse the damage when he snaps.",
    "IYKYK: A calm MMC is just a storm waiting for the right reason.",
    "IYKYK: The quiet man is always the most dangerous one in the room.",
    "IYKYK: If the tension starts early the chaos will be legendary.",
    "IYKYK: Romance readers detect obsession faster than detectives.",
    "IYKYK: When he goes silent, the situation is already handled.",
    "IYKYK: The calm ones always have the most violent loyalty.",
    "IYKYK: If he’s observant, the plot is about to shift."
  ],

  reader_mood: [
    "Some days I want coffee. Other days I want a morally gray billionaire with control issues.",
    "My reading mood depends entirely on how unhinged the male lead is.",
    "If the man isn’t obsessed by chapter five, I’m already bored.",
    "My TBR is mostly emotionally unstable men and women who can handle them.",
    "Books are cheaper than therapy and way more entertaining.",
    "My reading mood depends entirely on how unstable the male lead is.",
    "I knew this book was dangerous the moment I said one more chapter.",
    "If the tension doesn’t make me nervous, I don’t want it.",
    "I read like someone hiding from reality.",
    "My emotional stability is currently in chapter thirty-two.",
    "Every suspicious character has my full attention.",
    "Mood: Watching the quiet man carefully.",
    "Mood: That man is suspiciously calm.",
    "Mood: Emotionally invested in a dangerous fictional man.",
    "Mood: Concerned but intrigued.",
    "Mood: Reading with my guard up.",
    "Mood: This man is not normal.",
    "Mood: I need chapter 27 immediately.",
    "Mood: That stare meant something.",
    "Mood: Emotionally compromised.",
    "Mood: I fear that man."
  ],

  bookish_luxury: [
    "Luxury is a full bookshelf and uninterrupted reading time.",
    "My idea of wealth is a library that requires a ladder.",
    "Expensive taste but my favorite place is still inside a book.",
    "Quiet rooms, heavy books, dangerous fictional men.",
    "Romance novels are my version of designer handbags.",
    "The richest feeling in the world is having time to read.",
    "A beautiful bookshelf is a personality trait.",
    "My taste in books is expensive and emotionally destructive.",
    "Luxury is reading without anyone interrupting the plot.",
    "Hardcover books feel like quiet wealth.",
    "My favorite luxury item is a full library."
  ],

  bde_energy: [
    "Confidence is attractive, but controlled dominance is addictive.",
    "I like men who don’t compete for attention. They command it.",
    "The room goes quiet when he walks in. I go quieter.",
    "Power is knowing he would burn the world down calmly.",
    "The most powerful men never need to announce themselves.",
    "Confidence is quiet when it’s real.",
    "The room shifts when certain men enter it.",
    "Real dominance is calm under pressure.",
    "Authority doesn’t ask for attention. It collects it."
  ],

  elite_dominance: [
    "Some men inherit power. Others build it from nothing.",
    "He doesn’t chase status. Status follows him.",
    "The most dangerous men never need to raise their voice.",
    "True dominance looks effortless.",
    "Some men inherit power. Others become it.",
    "He doesn’t compete. He replaces.",
    "The scariest men in the room are usually the quietest.",
    "Wealth changes how a man moves through the world.",
    "True power rarely needs witnesses."
  ],

  boss_woman: [
    "I don’t need saving. I need a man intelligent enough not to get in my way.",
    "Ambition looks good on me.",
    "I built my own throne. He just sits beside it.",
    "Success is the best revenge and the best accessory.",
    "I didn’t become this confident by accident.",
    "Ambition looks better on me than doubt ever did.",
    "I built the life I used to daydream about.",
    "My standards upgraded the moment my self-respect did.",
    "Being powerful is quieter than people expect."
  ],

  girly_feminine: [
    "Being feminine doesn’t mean being fragile.",
    "Lip gloss, intelligence, and excellent decision making.",
    "Soft voice, sharp instincts.",
    "Pretty girls can be dangerous too.",
    "Softness is a strength when it’s protected by boundaries.",
    "Pretty girls can still be extremely strategic.",
    "Being feminine has never meant being weak.",
    "Grace and discipline make a dangerous combination.",
    "Looking delicate doesn’t mean thinking small."
  ],

  paranormal: [
    "If he’s immortal and still obsessed with me, I must be doing something right.",
    "Loving a supernatural man means accepting chaos as a lifestyle.",
    "Immortality sounds boring until he meets the right woman.",
    "Monsters are less scary when they love you.",
    "Immortal men fall harder because time means nothing to them.",
    "Monsters are less scary when they love you.",
    "Supernatural devotion hits different.",
    "Eternal life sounds better with the right woman beside it.",
    "Even creatures of the night have favorite people."
  ],

  thriller: [
    "I knew the moment I met him that peace was no longer an option.",
    "Danger feels different when the man beside you is worse.",
    "He doesn’t run from trouble. Trouble runs calculations.",
    "Survival is easier when the most dangerous man in the room loves you.",
    "If the story feels calm, the danger is already nearby.",
    "I trust the quiet characters the least.",
    "The best thrillers make you suspicious of everyone.",
    "Some secrets are louder than gunshots.",
    "The truth always hides in the smallest detail."
  ],

  dangerous_mmc: [
    "He said mine like he already cleared the room. I fear that man.",
    "That man doesn’t argue. He adjusts outcomes. I fear that man.",
    "He looked at me like patience was running out. I fear that man.",
    "He didn’t ask what happened. He asked who. I fear that man.",
    "He noticed something nobody else did. I fear that man.",
    "That man studies people like case files. I fear that man.",
    "He didn’t react. He recalculated. I fear that man.",
    "He said handle it like the problem was already solved. I fear that man.",
    "He listens quietly and remembers everything. I fear that man.",
    "That man walks in calm and the room reorganizes itself. I fear that man.",
    "That man is polite in a way that feels threatening.",
    "He’s calm like consequences are already scheduled.",
    "That man doesn’t rush because he knows the ending.",
    "His patience feels expensive.",
    "That man speaks softly like he owns time.",
    "He moves like outcomes belong to him.",
    "That man isn’t loud. He’s certain.",
    "His silence does most of the talking.",
    "That man doesn’t repeat himself.",
    "He moves like the world eventually agrees with him."
  ],

  quiet_menace_mmc: [
    "The room can’t calm him. She can.",
    "That man listens when she speaks quietly.",
    "The storm pauses when she looks at him.",
    "Everyone else argues. She just says his name.",
    "He ignores the room but hears her.",
    "That man settles the moment she touches the conversation.",
    "The chaos stops when she shows up.",
    "She’s the only person who slows him down.",
    "That man listens differently when it’s her.",
    "The anger fades when she speaks calmly.",
    "Everyone else gets tension. She gets patience.",
    "That man adjusts when she asks.",
    "The storm respects her voice.",
    "He listens to her like instructions.",
    "That man calms when she’s near.",
    "Everyone else negotiates. She decides.",
    "The tension drops when she walks in.",
    "That man softens at her voice.",
    "The room can’t control him. She can.",
    "He quiets down when she looks at him."
  ],

  provider_alpha_mmc: [
    "That man protects her peace professionally.",
    "He handles problems before she notices them.",
    "Providing for her is personal.",
    "He secures her life quietly.",
    "That man builds safety around her.",
    "He moves like her comfort is the mission.",
    "Protection comes naturally to him.",
    "He treats her security like responsibility.",
    "That man removes obstacles calmly.",
    "He guards her happiness carefully.",
    "Providing for her feels natural.",
    "He keeps her life soft on purpose.",
    "That man builds a safe world around her.",
    "He handles chaos so she doesn’t have to.",
    "Protection is instinct for him.",
    "He invests in her peace.",
    "That man solves problems silently.",
    "He prioritizes her stability.",
    "Providing is how he loves.",
    "He protects her future."
  ],

  obsessed_disciplined_mmc: [
    "That man is obsessed with control first and me second.",
    "His obsession has rules.",
    "That man loves like a man who still keeps discipline.",
    "He’s obsessed but composed.",
    "His devotion looks organized.",
    "That man is obsessed but patient.",
    "He doesn’t rush affection.",
    "His obsession moves carefully.",
    "That man loves intentionally.",
    "He’s obsessed but calculated.",
    "His devotion follows structure.",
    "That man controls his impulses.",
    "He’s obsessed but thoughtful.",
    "His attention feels measured.",
    "That man loves with restraint.",
    "He’s obsessed but strategic.",
    "His devotion feels consistent.",
    "That man loves responsibly.",
    "He’s obsessed but respectful.",
    "His attention feels disciplined."
  ],

  down_bad_mmc: [
    "That man is dangerously in love and not hiding it.",
    "He said her name like a decision he already made.",
    "Everyone else saw obsession. She saw devotion.",
    "That man is down bad and moving accordingly.",
    "He fell first, hardest, and permanently.",
    "The room knew before she did.",
    "He watches her like she’s the only plan that matters.",
    "He lost interest in the world the moment he met her.",
    "That man is gone for her.",
    "He doesn’t flirt. He commits aggressively.",
    "He folded instantly and never recovered.",
    "Everyone else is background noise.",
    "He’s down bad with excellent self control.",
    "That man is loyal like it’s a contract.",
    "He looks at her like the ending is already decided.",
    "The man never stood a chance.",
    "He’s not subtle about loving her.",
    "That man is embarrassingly devoted.",
    "He said her name and meant forever.",
    "He doesn’t pretend he’s okay without her."
  ],

  public_claim_mmc: [
    "He didn’t whisper it. He made it clear.",
    "That man chose her where everyone could see.",
    "He never hid her.",
    "The room knew who he belonged to.",
    "He stood beside her like a declaration.",
    "He didn’t keep her quiet.",
    "He said her name with witnesses.",
    "Everyone saw the decision.",
    "He chose her out loud.",
    "He never made her feel secret.",
    "The city knew who had his loyalty.",
    "He claimed her without hesitation.",
    "The man made it obvious.",
    "He introduced her like a title.",
    "No confusion about who she was.",
    "He said it once and meant it publicly.",
    "Everyone understood the assignment.",
    "He chose her without negotiation.",
    "That man never played about her.",
    "He stood ten toes behind her."
  ],

  wife_energy_mmc: [
    "That man moves like he already married her.",
    "He treats her like a lifelong decision.",
    "That’s husband behavior.",
    "He protects her like paperwork already exists.",
    "The man acts like vows are pending.",
    "He moves like she’s already family.",
    "That’s wife treatment.",
    "He loves her like permanence.",
    "That man behaves like commitment is obvious.",
    "He’s already planning forever.",
    "The man acts like the future is settled.",
    "That’s spouse energy.",
    "He moves like she’s already home.",
    "The man invests like she’s permanent.",
    "He treats her like legacy.",
    "That’s marriage mindset.",
    "He moves carefully with her heart.",
    "The man behaves like vows are coming.",
    "He plans life with her included.",
    "That’s lifelong partner energy."
  ],

  jealous_controlled_mmc: [
    "He doesn’t cause scenes. He causes adjustments.",
    "His jealousy isn’t loud. It’s strategic.",
    "That man doesn’t argue over attention. He reclaims it.",
    "You can’t see his jealousy. You can only see the results.",
    "He doesn’t get emotional. He gets observant.",
    "His jealousy looks like quiet correction.",
    "That man doesn’t confront immediately. He calculates first.",
    "He doesn’t react. He responds.",
    "His jealousy moves slower than anger.",
    "That man watches carefully before acting.",
    "He doesn’t compete. He replaces.",
    "His jealousy shows up as patience.",
    "That man notices everything.",
    "He doesn’t interrupt conversations. He ends them later.",
    "His jealousy looks like calm focus.",
    "That man studies behavior.",
    "He doesn’t raise his voice. He lowers tolerance.",
    "His jealousy sharpens his attention.",
    "That man remembers details.",
    "He doesn’t get insecure. He gets deliberate."
  ],

  strategy_mmc: [
    "That man studies the room before he speaks.",
    "He clocks every exit before he sits down.",
    "That man listens first and moves second.",
    "He reads the room like strategy.",
    "That man notices everything.",
    "He walks in already aware.",
    "That man pays attention to what people miss.",
    "He reads silence better than conversation.",
    "That man observes before he reacts.",
    "He measures people quietly.",
    "That man watches me like he’s studying a winning move.",
    "The way he looks at me feels intentional.",
    "He doesn’t stare. He evaluates.",
    "That man studies me like important information.",
    "The way he watches me feels planned.",
    "He doesn’t glance. He analyzes.",
    "That man pays attention like it matters.",
    "The way he watches me feels deliberate.",
    "He doesn’t just look. He notices.",
    "That man observes details other people miss."
  ],

  expensive_dangerous_mmc: [
    "That man looks expensive and extremely not safe.",
    "He looks like trouble with a tailored suit.",
    "Luxury and danger in the same silhouette.",
    "That man dresses like money and moves like a warning.",
    "He looks like someone important told him no once.",
    "Expensive watch. Dangerous patience.",
    "That man looks like a bad decision with excellent credit.",
    "Money in the details. Menace in the silence.",
    "He looks like he owns the room and the consequences.",
    "That man looks calm in a way that costs money.",
    "Tailored suit. Unspoken threats.",
    "He looks like wealth with a temper.",
    "That man carries danger like an accessory.",
    "Expensive taste. Dangerous instincts.",
    "He looks like someone who wins quietly.",
    "That man looks like strategy in designer.",
    "Luxury on the outside. Pressure underneath.",
    "He looks like the man problems call.",
    "That man looks like money and unfinished business.",
    "Expensive silence. Dangerous eyes."
  ],

  calm_authority_mmc: [
    "That man doesn’t raise his voice. He raises standards.",
    "Authority sits comfortably on him.",
    "That man speaks once and the room adjusts.",
    "He carries leadership quietly.",
    "That man doesn’t demand respect. He receives it.",
    "Authority follows him naturally.",
    "That man moves like the outcome is already decided.",
    "He commands attention without asking.",
    "That man handles situations calmly.",
    "Authority looks effortless on him.",
    "He leads without noise.",
    "That man moves with quiet certainty.",
    "Authority recognizes itself in him.",
    "He speaks and people listen.",
    "That man handles pressure easily.",
    "Authority comes from confidence.",
    "He controls the pace of the room.",
    "That man remains calm under stress.",
    "Authority without arrogance.",
    "He moves with decisive patience."
  ],

  soft_voice_serious_mmc: [
    "He speaks softly but means everything he says.",
    "That man talks quietly and changes the room.",
    "His voice is calm but the message is firm.",
    "He doesn’t need volume to be understood.",
    "That man speaks gently and expects compliance.",
    "His voice stays soft even when he’s serious.",
    "He speaks quietly and people listen closely.",
    "That man keeps his tone low and his standards high.",
    "He speaks calmly but leaves no confusion.",
    "That man doesn’t raise his voice.",
    "His quiet tone carries weight.",
    "He speaks softly and commands attention.",
    "That man keeps conversations controlled.",
    "His calm voice hides sharp decisions.",
    "He speaks quietly but firmly.",
    "That man chooses his words carefully.",
    "His tone stays level under pressure.",
    "He speaks softly and people take him seriously.",
    "That man doesn’t waste words.",
    "His voice remains steady."
  ],

  provider_unhinged_mmc: [
    "He pays the bills and solves problems aggressively.",
    "Provider energy with questionable patience.",
    "That man funds peace and destroys problems.",
    "Soft life sponsor. Chaos manager.",
    "He provides generously and protects irrationally.",
    "That man handles the finances and the nonsense.",
    "Luxury funded. Problems eliminated.",
    "He spoils her properly and overreacts professionally.",
    "Provider mindset. Unhinged loyalty.",
    "That man budgets carefully and defends recklessly.",
    "He secures her life and shortens arguments.",
    "Provider behavior. Menace tendencies.",
    "That man funds comfort and removes obstacles personally.",
    "He handles the money and the threats.",
    "Provider instinct. Violent devotion.",
    "That man believes in peace… after he handles it.",
    "He builds the life and guards the door.",
    "Provider energy with feral follow-through.",
    "That man protects the investment emotionally.",
    "He funds her happiness and monitors the room."
  ],

  she_calms_him: [
    "The room can’t calm him. She can.",
    "That man listens when she speaks quietly.",
    "The storm pauses when she looks at him.",
    "Everyone else argues. She just says his name.",
    "He ignores the room but hears her.",
    "That man settles the moment she touches the conversation.",
    "The chaos stops when she shows up.",
    "She’s the only person who slows him down.",
    "That man listens differently when it’s her.",
    "The anger fades when she speaks calmly."
  ],

  he_only_chases_her: [
    "He doesn’t chase women. He chose one and closed the application process.",
    "That man ignores attention like it’s background noise. But when I walk in, suddenly he’s interested.",
    "Women flirt with him constantly. He only answers when I speak.",
    "He doesn’t pursue. He selects.",
    "That man could have anyone in the room. And somehow he’s watching me like I’m the only option.",
    "He doesn’t entertain women. He evaluates one.",
    "The man never chased a day in his life. He just decided I was worth the effort.",
    "Women approach him. He approaches me.",
    "That man doesn’t waste time collecting attention. He invests it.",
    "He ignores the crowd. But somehow he always finds me."
  ],

  everyone_fears_him_except_her: [
    "The room goes silent when he walks in. I just ask if he ate.",
    "Everyone fears that man. I tell him when he’s being dramatic.",
    "The city respects his temper. I roll my eyes at it.",
    "Men watch their words around him. I interrupt him mid sentence.",
    "The room walks carefully around him. I walk straight up to him.",
    "Everyone calls him dangerous. I call him by his first name.",
    "The city fears him. I tease him.",
    "Everyone respects the threat. I respect the man.",
    "The room studies his reactions. I study his moods.",
    "Men lower their voices around him. I raise an eyebrow."
  ],

  city_respects_her_because_of_him: [
    "No one taught the city my name. They learned it from his loyalty.",
    "Respect follows me because it follows him.",
    "The city learned quickly who not to disrespect.",
    "No one needed an explanation. They saw how he looked at me.",
    "The city didn’t ask questions. They observed his devotion.",
    "Respect came automatically once he stood beside me.",
    "Nobody confused my position.",
    "The city knew whose woman I was.",
    "People greet me carefully now.",
    "Respect became routine."
  ],

  he_said_mine_quietly: [
    "He didn’t raise his voice. He just said mine like the conversation was already finished.",
    "The way he said mine sounded less like romance and more like policy.",
    "He didn’t argue with the room. He just said mine and everyone adjusted.",
    "That man said mine like a quiet warning.",
    "He didn’t repeat himself. He didn’t need to.",
    "The word mine left his mouth like ownership with manners.",
    "He said mine the way powerful men sign documents.",
    "Not loud. Not dramatic. Just mine.",
    "He didn’t say it twice because he never has to.",
    "The word mine sounded calm enough to be terrifying.",
    "He said mine like a man correcting a public mistake.",
    "The way he said mine sounded patient and permanent.",
    "He didn’t emphasize the word. He stabilized it.",
    "He said mine like the room had been misinformed.",
    "Not possessive. Precise.",
    "He said mine like a verdict already written.",
    "That man didn’t stake a claim. He clarified jurisdiction.",
    "The word mine sounded like the end of speculation.",
    "He didn’t defend the statement. He expected it to hold.",
    "He said mine like gravity—quiet but undeniable."
  ],

  black_romance_devotion: [
    "Soft For Her Only",
    "The Man Who Chose Her",
    "The Woman He Protects",
    "The Only One He Listens To",
    "The Woman He Watches",
    "The Man Who Said Mine",
    "The Woman Who Changed Him",
    "The Man Who Stood Beside Her",
    "The Woman Who Calms Him",
    "The Man Who Doesn’t Play About Her",
    "The Woman Who Gets His Patience",
    "The Man Who Picks One Woman",
    "The Woman Who Holds His Attention",
    "The Man Who Stays Loyal",
    "The Woman Who Has His Loyalty",
    "The Man Who Doesn’t Share",
    "The Woman He Chose Publicly",
    "The Man Who Guards Her Peace",
    "The Woman Who Has His Focus",
    "The Man Who Moves For Her"
  ],

  street_king_soft_for_her: [
    "Street King. Soft For Her.",
    "The City Fears Him. She Doesn’t.",
    "The Block Knows Him. She Knows Him Better.",
    "Dangerous Man. Gentle With Her.",
    "Ruthless King. Soft Husband.",
    "The Streets Get Steel. She Gets Silk.",
    "The City Gets Silence. She Gets Conversation.",
    "The Block Gets Business. She Gets Devotion.",
    "The King Bows Only To Her.",
    "Everyone Gets The Boss. She Gets The Man."
  ],

  obsessed_rich_man_hood_girl: [
    "Rich Man. Hood Girl.",
    "Billionaire From The Block.",
    "Luxury Man. Hood Princess.",
    "Money Meets The Block.",
    "Penthouse Meets The Projects.",
    "Rich Man. Street Smart Girl.",
    "He Has Money. She Has Nerve.",
    "Wealthy Man. Hood Queen.",
    "Luxury Life. Hood Loyalty.",
    "The Billionaire Loves The Hood Girl."
  ],

  street_king_soft_life: [
    "The streets fear him. She schedules his peace.",
    "City king. Soft life queen.",
    "He runs the block. She runs the mood.",
    "Street power. Soft life energy.",
    "The city gets the boss. She gets the man.",
    "Dangerous reputation. Gentle husband.",
    "He handles the streets. She handles his heart.",
    "Street king discipline. Soft life reward.",
    "The block respects him. He spoils her.",
    "He brings the power. She brings the peace.",
    "Street loyalty meets soft life standards.",
    "The city knows his name. He knows her coffee order.",
    "Street king strategy. Soft life comfort.",
    "He rules the streets. She rules the house.",
    "Dangerous man. Delicate treatment."
  ],

  black_dark_romance_obsession: [
    "Obsessed Black MMC",
    "Black Dark Romance King",
    "Devotion With Teeth",
    "Possessive Black Hero",
    "Obsessed From Chapter One",
    "Dangerous Black Devotion",
    "Black Villain Romance",
    "Obsessive Black Love",
    "Black Antihero Love",
    "Possession Without Apology",
    "Territorial Black Hero",
    "Ruthless For His Woman",
    "Obsessed Black Alpha",
    "The Man Who Watches",
    "Dangerous Black Protector"
  ],

  black_romance_kindle_highlights: [
    "He didn’t look at me like a man interested in options. He looked at me like a man who had already decided.",
    "The room kept talking, but his attention stayed exactly where he left it—on me.",
    "That man never rushed anything. Except the moment he realized I was his problem.",
    "He watched me like a man who planned to remember everything.",
    "I knew I was in trouble the moment he stopped pretending not to notice me.",
    "He didn’t flirt. He evaluated.",
    "That man looked at me like patience was about to run out.",
    "Everyone else saw his reputation. I saw the way he paid attention.",
    "He didn’t interrupt the conversation. He just ended it when I walked in.",
    "That man didn’t chase women. He made decisions.",
    "He watched me like I was the only variable he hadn’t solved yet.",
    "The way he said my name sounded dangerously deliberate.",
    "He didn’t smile often, but when he did it felt like a private victory.",
    "That man listened the way powerful men listen—quietly and completely.",
    "I noticed him noticing me long before anyone else did.",
    "He looked at me like strategy.",
    "That man didn’t waste attention. Which made it terrifying when he gave it to me.",
    "He studied me like the answer mattered.",
    "The first time he said my name, the room felt smaller.",
    "He didn’t hover. He positioned himself."
  ]
};
