export const TROPE_BANK = {
  classic_romance: [
    "Only One Bed",
    "Grumpy Sunshine",
    "Enemies To Lovers",
    "Friends To Lovers",
    "Fake Dating Situation",
    "Marriage Of Convenience",
    "Second Chance Romance",
    "Secret Billionaire",
    "Forbidden Love",
    "Forced Proximity",
    "Slow Burn Chaos",
    "Accidental Marriage",
    "Secret Identity Reveal",
    "Childhood Friends To Lovers",
    "Reformed Villain Arc",
    "Opposites Attract",
    "Love Triangle Survivor",
    "Protective Bodyguard",
    "Touch Her And Die",
    "He Falls First",
    "She Falls Harder",
    "Hidden Royalty Trope",
    "Small Town Romance",
    "City Girl Meets Trouble",
    "Runaway Bride Energy",
    "Reluctant Protector",
    "Jealousy Awakening",
    "Protective Alpha Trope",
    "Danger Brings Them Closer",
    "Unexpected Heir"
  ],

  dark_romance: [
    "Touch Her And Die",
    "Morally Gray Man",
    "Possessive Love Interest",
    "Obsessed Male Lead",
    "Villain Gets The Girl",
    "Kidnapping But Make It Devotion",
    "Dangerous Protector",
    "Ruthless For Her Only",
    "Protective Villain",
    "Devotion With Violence",
    "Obsessive Protection",
    "Territorial MMC",
    "Dangerous Loyalty",
    "Devoted Antihero",
    "Ruthless Provider",
    "Violent Devotion",
    "Claimed Energy",
    "Possession Trope",
    "Deadly Protector",
    "Calm But Deadly",
    "Soft For Her Only",
    "Silent Enforcer",
    "Obsessed From The Start",
    "The Man Everyone Fears",
    "Dangerous Man Soft Spot",
    "Villain Redemption Arc",
    "Protective Crime Boss",
    "Touch Him And Die",
    "War For Her",
    "Territorial Alpha"
  ],

  black_booktok_urban_romance: [
    "Street King MMC",
    "Hood King Romance",
    "Block Royalty Couple",
    "Hustler To Husband",
    "Boss Lady x Street King",
    "Ride Or Die Love",
    "Loyalty Over Everything",
    "Hood Love Story",
    "Trench Love Romance",
    "King Of The City",
    "Street Loyalty Romance",
    "Real One Energy",
    "Provider Energy MMC",
    "Street Smart Romance",
    "Bossed Up Couple",
    "Protective Hood Hero",
    "Dangerous Loyalty Trope",
    "City King Protector",
    "Respect The Queen Energy",
    "Block Royalty Love",
    "Paid And Protective",
    "Dangerous Man Soft Spot",
    "Empire Builder Romance",
    "Street Loyalty Devotion",
    "King And His Queen",
    "Hood Billionaire Energy",
    "Provider Protector Trope",
    "Boss Couple Energy",
    "Money Power Loyalty",
    "Respect Runs The City"
  ],

  black_romance: [
    "Soft Black Love",
    "Black Girl Soft Life",
    "Black Love Story",
    "Black Romance Royalty",
    "Black Love Always Wins",
    "Healing Through Love",
    "Black Girl Main Character",
    "Black Joy Romance",
    "Black Queen Energy",
    "Black Love Legacy",
    "Black Girl Protected",
    "Black Love Era",
    "Black Romance Reader",
    "Black Girl Luxury",
    "Black Love First",
    "Black Queen Treatment",
    "Black Love Healing",
    "Black Girl Deserves Softness",
    "Black Romance Culture",
    "Black Love Celebration",
    "Black Couple Goals",
    "Black Girl Peace Era",
    "Black Romance Energy",
    "Black Girl Thriving",
    "Black Love And Loyalty",
    "Black Woman Cherished",
    "Black Love Dynasty",
    "Black Girl Protected Era",
    "Black Love Excellence",
    "Black Queen Energy"
  ],

  hood_billionaire_romance: [
    "Hood Billionaire Romance",
    "Trap To Tycoon",
    "Street King Billionaire",
    "From The Block To Billions",
    "Hood Rich Hero",
    "Self Made King",
    "Trap Boy Turned Mogul",
    "Street Empire Builder",
    "Hood Billionaire Energy",
    "Luxury From The Hustle",
    "Paid And Dangerous",
    "Hood Royalty Romance",
    "Street Money Billionaire",
    "Built Different Billionaire",
    "Trap To Private Jets",
    "Block Legend To Billionaire",
    "Street Smart Billionaire",
    "Hood King With Billions",
    "Money Power Loyalty",
    "From Corners To Corporate",
    "Street Made Millionaire",
    "Empire From The Trenches",
    "Hood Boss Billionaire",
    "Street King With Assets",
    "Hood Billionaire Era",
    "Luxury From Loyalty",
    "Street Money Dynasty",
    "Block Built Billionaire",
    "Self Made Street King",
    "Trap King To Tycoon"
  ],

  street_loyalty_mmc: [
    "Street Loyalty MMC",
    "Real One Hero",
    "Loyalty Over Everything",
    "Ride Or Die Devotion",
    "Street Loyal Man",
    "The Man Who Handles It",
    "Silent Protector MMC",
    "Block Loyal Hero",
    "He Don’t Play About Her",
    "Street Code Romance",
    "Stand On Business MMC",
    "Respect First Hero",
    "Street Loyalty Love",
    "Real One Energy",
    "Ten Toes Down Hero",
    "Solid Man Energy",
    "Loyalty Is Law",
    "Street Code Devotion",
    "Respect The Queen MMC",
    "He Moves Different",
    "The Calm Enforcer",
    "Quiet But Deadly Hero",
    "Street King Protector",
    "He Handles Problems",
    "The Man The Block Respects",
    "Loyalty First Love",
    "Ride Or Die Couple",
    "The Man Who Shows Up",
    "Solid Man Devotion",
    "Street Honor Romance"
  ],

  soft_life_dangerous_man: [
    "Soft Life Dangerous Man",
    "Luxury And A Loaded Man",
    "Soft Girl Protected",
    "Peace With A Menace",
    "Silk Sheets And Street Kings",
    "Soft Life Security",
    "Dangerous Man Soft Spot",
    "Luxury Guarded By Violence",
    "Calm Life Violent Protector",
    "Soft Girl Dangerous Love",
    "Soft Life With A King",
    "Pretty Girl Protected",
    "Luxury And Loyalty",
    "Soft Girl Safe Here",
    "Gentle Life Rough Man",
    "Spoiled And Secured",
    "Soft Girl Dangerous Husband",
    "Luxury Protected Energy",
    "Soft Life With A Problem",
    "Soft Girl Security Detail",
    "Peace Guarded By Him",
    "Luxury Life Enforcer",
    "Soft Girl Mafia Adjacent",
    "Dangerous Man Domestic",
    "Soft Life Street King",
    "Peaceful Life Dangerous Man",
    "Protected Soft Life",
    "Luxury With Protection",
    "Pretty Girl Security",
    "Soft Life Alpha"
  ],

  black_dark_romance_obsession: [
    "Obsessed Black MMC",
    "Black Dark Romance King",
    "Devotion With Teeth",
    "Possessive Black Hero",
    "Obsessed From Chapter One",
    "Dangerous Black Devotion",
    "Black Villain Romance",
    "Obsessive Black Love",
    "Black Antihero Love",
    "Possession Without Apology",
    "Territorial Black Hero",
    "Ruthless For His Woman",
    "Obsessed Black Alpha",
    "The Man Who Watches",
    "Dangerous Black Protector",
    "Devoted Black Villain",
    "Black MMC Obsession",
    "Possessive Black King",
    "Black Romance Antihero",
    "Obsessed Hero Energy",
    "Black MMC Possession",
    "Devoted Black Menace",
    "The Man Who Decides",
    "Black Dark Romance Alpha",
    "Black Obsession Trope",
    "Ruthless Devotion MMC",
    "Black Romance Enforcer",
    "Dangerous Black Loyalty",
    "Obsessed Protector Trope",
    "Black Villain Devotion"
  ],

  urban_power_couple: [
    "Urban Power Couple",
    "King And His Queen",
    "Boss Couple Energy",
    "City Power Couple",
    "Hood Royalty Couple",
    "Street King And Queen",
    "Empire Building Couple",
    "Bossed Up Love",
    "Paid And Powerful Pair",
    "Dangerous Love Duo",
    "The City’s Favorite Couple",
    "Block Royalty Pair",
    "Money Power Couple",
    "Kingdom Building Romance",
    "Boss Love Story",
    "Respect The Queen Energy",
    "Street Empire Couple",
    "Power Moves Together",
    "City Running Couple",
    "Street Throne Couple",
    "Luxury Power Couple",
    "Boss Couple Dynasty",
    "Hood Elite Couple",
    "Empire Couple Energy",
    "Street Dynasty Romance",
    "Power Couple Loyalty",
    "City Boss Romance",
    "Street Crown Couple",
    "King And His Empress",
    "Urban Royalty Romance"
  ],

  loving_unhinged_black_mmc: [
    "Loving Unhinged Hero",
    "Devoted And Dangerous",
    "Obsessed With His Woman",
    "Unhinged But Loyal",
    "Loyal To A Fault",
    "Devotion Without Limits",
    "Loving Menace Energy",
    "Unhinged Devotion Trope",
    "Protective And Problematic",
    "Devoted Chaos MMC",
    "Unhinged For Her Only",
    "Dangerously Devoted",
    "Ruthless But Romantic",
    "Emotionally Unstable For Her",
    "Love Made Him Worse",
    "Devotion Made Him Dangerous",
    "Unhinged Love Interest",
    "Obsessed Protector MMC",
    "Violent Devotion Energy",
    "The Man Who Lost His Mind For Her",
    "Devoted Chaos Hero",
    "Unhinged Love Story",
    "Obsessed Alpha Energy",
    "Dangerous Devotion Trope",
    "Loyal Villain Romance",
    "Possessive Devotion MMC",
    "Unstable But Faithful",
    "Love Turned Him Ruthless",
    "Feral Devotion MMC",
    "Devoted Problematic King",
    "The Man Who Chose Violence",
    "Unhinged Loyalty Trope",
    "Love Made Him Territorial",
    "Dangerous Love Interest",
    "Devoted Menace MMC",
    "Ruthless Romantic Hero",
    "Love Turned Him Savage",
    "Devotion Without Mercy",
    "Possessive Love Energy",
    "Loyalty Gone Too Far",
    "Devoted Chaos Romance",
    "Unhinged But Gentle With Her",
    "Feral Devotion Energy",
    "Dangerous Man In Love",
    "Obsessed And Loyal",
    "Loving But Unstable",
    "Devoted Villain Energy",
    "Love Made Him Reckless",
    "Unhinged Protector MMC",
    "Obsessed Devotion Trope"
  ],

  quiet_menace_mmc: [
    "Quiet Menace Hero",
    "Silent Danger MMC",
    "Calm But Terrifying",
    "The Man Who Watches",
    "Quiet Authority MMC",
    "Silent Enforcer Energy",
    "The Man Who Doesn’t Repeat Himself",
    "Quiet But Deadly",
    "Silent Power MMC",
    "Calm Control Energy",
    "Quiet King Energy",
    "Silent Protector Trope",
    "The Man Who Moves Quiet",
    "Quiet Man Dangerous",
    "The Calmest Man In The Room",
    "Silent Strategy MMC",
    "Danger In Silence",
    "The Man Who Observes",
    "Quiet Power Romance",
    "Silent Domination MMC",
    "The Man Who Doesn’t Bluff",
    "Silent Threat Energy",
    "Quiet Man With Power",
    "Stillness Before Violence",
    "The Man Who Already Knows",
    "Quiet Authority Romance",
    "Silent Pressure MMC",
    "The Man Who Handles It",
    "Quiet Menace Love",
    "Silent Alpha Energy",
    "The Calm One Is Worse",
    "The Man Who Doesn’t Talk Much",
    "Quiet King Protector",
    "Silent Control MMC",
    "Quiet Dominance Trope",
    "The Man Who Doesn’t Need To Yell",
    "Still Waters MMC",
    "Quiet Power Couple",
    "The Observant Man",
    "Silent Strategy King",
    "The Man Who Watches The Room",
    "Quiet But In Charge",
    "The Calm Alpha",
    "The Man Who Already Decided",
    "Silent Danger Romance",
    "Quiet King Behavior",
    "The Man Who Moves Strategically",
    "Quiet Control Energy",
    "Silent Alpha Protector",
    "Calm Menace MMC"
  ],

  provider_alpha_mmc: [
    "Provider Alpha MMC",
    "Provider King Energy",
    "Spoil Her Properly",
    "The Man Who Funds Her Peace",
    "Provider Protector MMC",
    "Luxury Provider Hero",
    "The Man Who Handles Everything",
    "Paid And Protective MMC",
    "Soft Life Provider",
    "Provider Husband Energy",
    "The Man Who Makes It Easy",
    "Financially Dangerous Man",
    "Provider Alpha Romance",
    "Luxury Life Provider",
    "The Man Who Provides Quietly",
    "Security First Hero",
    "Spoiled Wife Energy",
    "The Man Who Solves Problems",
    "Provider King Romance",
    "Alpha Provider Energy",
    "The Man Who Builds Empires",
    "Provider Husband Trope",
    "Luxury Lifestyle Alpha",
    "Financially Elite Protector",
    "The Man Who Secures The Future",
    "Provider King Devotion",
    "Soft Life Alpha Husband",
    "The Man Who Pays Attention",
    "Security And Stability Hero",
    "The Man Who Handles Business",
    "Provider Man Energy",
    "Elite Provider Romance",
    "Alpha Who Provides Peace",
    "The Man Who Funds Her Dreams",
    "Provider Protector Energy",
    "The Man Who Moves Resources",
    "Spoiled And Secured Trope",
    "Luxury Provider King",
    "The Man Who Makes It Happen",
    "Provider Alpha Dynasty",
    "The Man Who Covers Everything",
    "Financial Security MMC",
    "Provider Power Couple",
    "Luxury Husband Energy",
    "Alpha Who Protects Peace",
    "The Man Who Handles The World",
    "Provider Man Of Action",
    "Elite Alpha Provider",
    "The Man Who Moves Money",
    "Provider King Behavior"
  ],

  shes_the_only_one_he_listens_to: [
    "She’s The Only One He Listens To",
    "The Only Woman He Respects",
    "The Only Voice He Hears",
    "The Woman Who Calms Him",
    "The Only One Who Can Stop Him",
    "The Woman Who Controls The Chaos",
    "The Only Woman He Obeys",
    "The One Who Tames The King",
    "The Woman Who Grounds Him",
    "The Only One He Softens For",
    "The Woman Who Holds His Attention",
    "The Only One He Takes Orders From",
    "The Woman Who Has His Ear",
    "The One Woman Exception",
    "The Only Woman He Bends For",
    "The Woman Who Commands Respect",
    "The One He Won’t Ignore",
    "The Only One Who Can Check Him",
    "The Woman Who Calls Him Out",
    "The One Who Keeps Him Balanced",
    "The Only One He Listens Carefully To",
    "The Woman Who Can Calm The Storm",
    "The Only One With Influence",
    "The Woman Who Moves Him",
    "The Only One Who Gets Through",
    "The Woman Who Stops The War",
    "The Only One Who Can Reach Him",
    "The Woman He Pays Attention To",
    "The One Who Breaks Through His Walls",
    "The Woman Who Speaks And He Listens",
    "The Only One Who Changes His Mind",
    "The Woman He Trusts Most",
    "The One Woman Rule",
    "The Woman Who Commands His Loyalty",
    "The Only One Who Can Correct Him",
    "The Woman Who Holds His Respect",
    "The One He Won’t Disrespect",
    "The Only One Who Can Challenge Him",
    "The Woman Who Can Tell Him No",
    "The Only One Who Can Move Him",
    "The Woman Who Runs His Heart",
    "The Only One Who Can Handle Him",
    "The Woman Who Softens The Beast",
    "The Only One Who Can Reach The King",
    "The Woman Who Holds His Loyalty",
    "The One He Protects The Most",
    "The Woman He Won’t Cross",
    "The Only One Who Can Stop Him",
    "The Woman Who Knows His Mind",
    "The One Woman He Listens To"
  ],

  he_doesnt_like_anyone_but_her: [
    "He Doesn’t Like Anyone Except Her",
    "He Tolerates One Person. Her.",
    "The Only Woman He Likes",
    "Everyone Annoys Him Except Her",
    "She’s The Only One He’s Nice To",
    "The Only Person He’s Patient With",
    "Everyone Else Gets Silence. She Gets Attention.",
    "He Ignores The World But Watches Her",
    "The Only One Who Makes Him Smile",
    "Everyone Else Is A Problem. She’s The Exception.",
    "He Doesn’t Talk Much Unless It’s To Her",
    "The Only Voice He Listens For",
    "He Doesn’t Care Unless It’s Her",
    "She’s The Only One He Makes Time For",
    "The Only Person He Softens For",
    "Everyone Else Gets Distance. She Gets Access.",
    "The Only One Who Gets His Humor",
    "The Only One Who Breaks His Focus",
    "The Only One He Lets Close",
    "The Only One He Lets In",
    "Everyone Else Gets Indifference. She Gets Devotion.",
    "The Only One Who Gets His Effort",
    "Everyone Else Is Noise. She’s The Signal.",
    "The Only One Who Interrupts His Silence",
    "Everyone Else Gets Tolerance. She Gets Loyalty.",
    "The Only One He Doesn’t Ignore",
    "The Only One Who Changes His Mood",
    "The Only One Who Gets His Time",
    "Everyone Else Gets Distance. She Gets Protection.",
    "The Only One He Prioritizes"
  ],

  touch_her_and_die_black_romance: [
    "Touch Her And Die",
    "Look At Her Wrong And It’s Over",
    "Play With Her And Meet God",
    "Disrespect Her And We Have A Problem",
    "That’s His Woman. Move Carefully.",
    "The City Knows That’s His",
    "Talk Crazy And See What Happens",
    "Everybody Knows Don’t Try Her",
    "He Don’t Play About Her",
    "Her Name Is Off Limits",
    "The Block Knows That’s His Girl",
    "Say Something Wrong And Find Out",
    "Everyone Watches How They Speak To Her",
    "Her Safety Is Non Negotiable",
    "He Handles Disrespect Personally",
    "The Warning Is Already Known",
    "You Don’t Test That Man’s Woman",
    "Everyone Moves Respectfully Around Her",
    "He Protects Without Announcement",
    "One Look And Everyone Understands",
    "That Woman Is Protected",
    "Disrespect Gets Addressed Immediately",
    "He Doesn’t Debate About Her",
    "Everyone Knows Where The Line Is",
    "The City Respects His Woman",
    "Try Her And Regret It"
  ],

  street_king_soft_for_her: [
    "Street King Soft For Her",
    "The City Fears Him She Doesn’t",
    "The Block Knows Him She Knows Him Better",
    "Dangerous Man Gentle With Her",
    "Ruthless King Soft Husband",
    "The Streets Get Steel She Gets Silk",
    "The City Gets Silence She Gets Conversation",
    "The Block Gets Business She Gets Devotion",
    "The King Bows Only To Her",
    "Everyone Gets The Boss She Gets The Man",
    "The City Gets Authority She Gets Affection",
    "He Rules The Streets She Rules Him",
    "Dangerous To Everyone Soft With Her",
    "The Streets Get Power She Gets Peace",
    "The King Gets Respect She Gets Love",
    "The City Sees Power She Sees His Heart",
    "The Block Knows The Legend She Knows The Man",
    "The King Runs The City She Runs His World",
    "The Streets Get Strategy She Gets Sweetness",
    "The King Gets Feared She Gets Cherished"
  ],

  obsessed_rich_man_hood_girl: [
    "Rich Man Hood Girl",
    "Billionaire From The Block",
    "Luxury Man Hood Princess",
    "Money Meets The Block",
    "Penthouse Meets The Projects",
    "Rich Man Street Smart Girl",
    "He Has Money She Has Nerve",
    "Wealthy Man Hood Queen",
    "Luxury Life Hood Loyalty",
    "The Billionaire Loves The Hood Girl",
    "Rich Man Street Girl Energy",
    "Luxury King Block Queen",
    "Old Money Hood Attitude",
    "The Billionaire Can’t Leave Her Alone",
    "Rich Man Hood Girl Problem",
    "Luxury Man Street Smart Woman",
    "The Billionaire Chose The Block",
    "Money Meets Loyalty",
    "Wealth Meets Real",
    "Luxury Man Hood Girl Rules"
  ]
};
